"""update: Attendance update

Revision ID: c199ad04ae09
Revises: f044b00ed11d
Create Date: 2025-04-06 14:32:43.342002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c199ad04ae09'
down_revision: Union[str, None] = 'f044b00ed11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('TProjectStatus',
    sa.Column('idProjectStatus', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idProjectStatus'),
    schema='admin'
    )
    
    op.add_column(
        'TProject',
        sa.Column("status", sa.Integer(), nullable=True),
        schema="admin"
        )
    
    op.create_foreign_key(
        'fk_TProject_status',
        'TProject',
        'TProjectStatus',
        local_cols=['status'],
        remote_cols=['idProjectStatus'],
        source_schema='admin',
        referent_schema='admin',
        ondelete='SET NULL',
        onupdate='CASCADE'
    )

    op.create_table('TAttendance',
    sa.Column('idEmployee', sa.Integer(), nullable=False),
    sa.Column('inTime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('outTime', sa.DateTime(), nullable=True),
    sa.Column('idProject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEmployee'], ['admin.TEmployee.idEmployee'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idProject'], ['admin.TProject.idProject'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idEmployee', 'inTime'),
    schema='admin'
    )
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TAttendance', schema='admin')
    op.drop_table('TProjectStatus', schema='admin')
    op.drop_constraint('fk_TProject_status', 'TProject', schema='admin', type_='foreignkey')
    op.drop_column('TProject', 'admin', schema='admin')
    # ### end Alembic commands ###
