"""initial migration

Revision ID: f044b00ed11d
Revises: 
Create Date: 2025-03-29 18:40:52.587624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f044b00ed11d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEmployeeLicense',
    sa.Column('idLicense', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idLicense'),
    schema='admin'
    )
    op.create_table('TEmployeeRole',
    sa.Column('idRole', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('idRole'),
    schema='admin'
    )
    op.create_table('TEmployee',
    sa.Column('idEmployee', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(length=10), nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('hireDate', sa.Date(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('inDate', sa.Date(), nullable=True),
    sa.Column('outDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['admin.TEmployeeRole.idRole'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idEmployee'),
    schema='admin'
    )
    op.create_table('TEmployeeLicensesMid',
    sa.Column('idEmployee', sa.Integer(), nullable=False),
    sa.Column('idLicense', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmployee'], ['admin.TEmployee.idEmployee'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idLicense'], ['admin.TEmployeeLicense.idLicense'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idEmployee', 'idLicense'),
    schema='admin'
    )
    op.create_table('TTeam',
    sa.Column('idTeam', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader'], ['admin.TEmployee.idEmployee'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idTeam'),
    schema='admin'
    )
    op.create_table('TEmployeeTeamMid',
    sa.Column('idTeam', sa.Integer(), nullable=False),
    sa.Column('idEmployee', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmployee'], ['admin.TEmployee.idEmployee'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idTeam'], ['admin.TTeam.idTeam'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idTeam', 'idEmployee'),
    schema='admin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TEmployeeTeamMid', schema='admin')
    op.drop_table('TTeam', schema='admin')
    op.drop_table('TEmployeeLicensesMid', schema='admin')
    op.drop_table('TEmployee', schema='admin')
    op.drop_table('TEmployeeRole', schema='admin')
    op.drop_table('TEmployeeLicense', schema='admin')
    # ### end Alembic commands ###
