import { endpoints } from "@/src/shared/api/endpoints"
import { fetcher } from "@/src/shared/api/httpClient"
import { Employee } from "@/src/shared/types"

export async function getEmployees(): Promise<Employee[]> {
	try {
		const response = await fetcher.get<{message: string, data: Employee[]}>(`${endpoints.employees}`)
		if (!response || !response.data) {
			throw new Error('No se encontraron empleados')
		}
		return response.data
	} catch (error) {
		console.error('Error al obtener los empleados:', error)
		throw new Error('Error al obtener los empleados')
	}
}

//[
    //     {
	// 		id: 'EMP001',
	// 		name: 'Luis Torres',
	// 		address: 'Calle 10 #123, CDMX',
	// 		phone_number: '555-123-4567',
	// 		email: 'luis.torres@empresa.com',
	// 		hire_date: '2021-04-15',
	// 		salary: 45000,			
	// 		in_time: '08:00',
	// 		out_time: '17:00',
	// 		password: 'hashedpassword1',
	// 		role: 'leader',
	// 		position: 'Frontend Developer',
	// 		status: 'active',
	// 		img: 'https://i.pravatar.cc/150?u=a042581f4e29026024d'
	// 	},
	// 	{
	// 		id: 'EMP002',
	// 		name: 'Ana Martínez',
	// 		address: 'Av. Reforma 456, CDMX',
	// 		phone_number: '555-234-5678',
	// 		email: 'ana.martinez@empresa.com',
	// 		hire_date: '2020-08-10',
	// 		salary: 48000,			
	// 		in_time: '09:00',
	// 		out_time: '18:00',
	// 		password: 'hashedpassword2',
	// 		role: 'admin',
	// 		position: 'Backend Developer',
	// 					status: 'active',
	// 		img: 'https://i.pravatar.cc/150?u=a042581f4e29026704d'
	// 	},
	// 	{
	// 		id: 'EMP003',
	// 		name: 'Jorge Ramírez',
	// 		address: 'Calle Sur 789, GDL',
	// 		phone_number: '555-345-6789',
	// 		email: 'jorge.ramirez@empresa.com',
	// 		hire_date: '2019-12-01',
	// 		salary: 42000,
	// 		in_time: '08:30',
	// 		out_time: '17:30',
	// 		password: 'hashedpassword3',
	// 		role: 'leader',
	// 		position: 'UI/UX Designer',
	// 		status: 'inactive',
	// 			img: 'https://i.pravatar.cc/150?u=15'
	// 	},
	// 	{
	// 		id: 'EMP004',
	// 		name: 'Elena Ruiz',
	// 		address: 'Calle 8 #888, Monterrey',
	// 		phone_number: '555-456-7890',
	// 		email: 'elena.ruiz@empresa.com',
	// 		hire_date: '2022-03-05',
	// 		salary: 50000,
	// 		in_time: '07:30',
	// 		out_time: '16:30',
	// 		password: 'hashedpassword4',
	// 		role: 'user',
	// 		position: 'Fullstack Developer',
	// 		status: 'active',
	// 			img: 'https://i.pravatar.cc/20?u=28'
	// 	},
	// 	{
	// 		id: 'EMP005',
	// 		name: 'Carlos Méndez',
	// 		address: 'Col. Centro 303, Puebla',
	// 		phone_number: '555-567-8901',
	// 		email: 'carlos.mendez@empresa.com',
	// 		hire_date: '2021-06-20',
	// 		salary: 38000,
	// 		in_time: '09:00',
	// 		out_time: '18:00',
	// 		password: 'hashedpassword5',
	// 		role: 'user',
	// 		position: 'QA Analyst',
	// 		status: 'active',
	// 			img: 'https://i.pravatar.cc/150?u=38'
	// 	},
	// 	{
	// 		id: 'EMP006',
	// 		name: 'María Fernández',
	// 		address: 'Calle Reforma 111, León',
	// 		phone_number: '555-678-9012',
	// 		email: 'maria.fernandez@empresa.com',
	// 		hire_date: '2020-11-15',
	// 		salary: 53000,
	// 		in_time: '08:00',
	// 		out_time: '17:00',
	// 		password: 'hashedpassword6',
	// 		role: 'admin',
	// 		position: 'Product Owner',
	// 		status: 'inactive',
	// 			img: 'https://i.pravatar.cc/150?u=29'
	// 	},
	// 	{
	// 		id: 'EMP007',
	// 		name: 'Daniel Rojas',
	// 		address: 'Zona Centro 777, Mérida',
	// 		phone_number: '555-789-0123',
	// 		email: 'daniel.rojas@empresa.com',
	// 		hire_date: '2018-02-01',
	// 		salary: 47000,
	// 		in_time: '08:00',
	// 		out_time: '17:00',
	// 		password: 'hashedpassword7',
	// 		role: 'leader',
	// 		position: 'Mobile Developer',
	// 		status: 'pending',
	// 			img: 'https://i.pravatar.cc/150?u=41'
	// 	},
	// 	{
	// 		id: 'EMP008',
	// 		name: 'Laura Castro',
	// 		address: 'Barrio Antiguo, Monterrey',
	// 		phone_number: '555-890-1234',
	// 		email: 'laura.castro@empresa.com',
	// 		hire_date: '2023-01-10',
	// 		salary: 40000,
	// 		in_time: '10:00',
	// 		out_time: '19:00',
	// 		password: 'hashedpassword8',
	// 		role: 'user',
	// 		position: 'Graphic Designer',
	// 		status: 'pending',
	// 		img: 'https://i.pravatar.cc/150?u=44'
	// 	},
	// 	{
	// 		id: 'EMP009',
	// 		name: 'Ricardo Salas',
	// 		address: 'Col. Industrial 999, CDMX',
	// 		phone_number: '555-901-2345',
	// 		email: 'ricardo.salas@empresa.com',
	// 		hire_date: '2017-07-23',
	// 		salary: 37000,
	// 		in_time: '08:00',
	// 		out_time: '17:00',
	// 		password: 'hashedpassword9',
	// 		role: 'user',
	// 		position: 'IT Support',
	// 		status: 'active',	
	// 		img: 'https://i.pravatar.cc/20'
	// 	},
	// 	{
	// 		id: 'EMP010',
	// 		name: 'Sofía Navarro',
	// 		address: 'Av. Universidad 456, CDMX',
	// 		phone_number: '555-012-3456',
	// 		email: 'sofia.navarro@empresa.com',
	// 		hire_date: '2021-10-01',
	// 		salary: 39000,
	// 		in_time: '09:30',
	// 		out_time: '18:30',
	// 		password: 'hashedpassword10',
	// 		role: 'user',
	// 		position: 'Content Strategist',
	// 		status: 'inactive',
	// 		img: 'https://i.pravatar.cc/20'
	// 	},
	// 	{
	// 		id: 'EMP011',
	// 		name: 'Fernando Díaz',
	// 		address: 'Col. Jardines 321, Querétaro',
	// 		phone_number: '555-123-4560',
	// 		email: 'fernando.diaz@empresa.com',
	// 		hire_date: '2019-05-19',
	// 		salary: 52000,
	// 		in_time: '08:00',
	// 		out_time: '17:00',
	// 		password: 'hashedpassword11',
	// 		role: 'admin',
	// 		position: 'Data Engineer',
	// 		status: 'pending',
	// 		img: 'https://i.pravatar.cc/20'
	// 	},
	// 	{
	// 		id: 'EMP012',
	// 		name: 'Isabel Romero',
	// 		address: 'Zona Rosa, CDMX',
	// 		phone_number: '555-234-5670',
	// 		email: 'isabel.romero@empresa.com',
	// 		hire_date: '2022-08-05',
	// 		salary: 41000,
	// 		in_time: '09:00',
	// 		out_time: '18:00',
	// 		password: 'hashedpassword12',
	// 		role: 'user',
	// 		position: 'Recruiter',
	// 		status: 'pending',
	// 		img: 'https://i.pravatar.cc/20'
	// 	},
	// 	{
	// 		id: 'EMP013',
	// 		name: 'Tomás Vargas',
	// 		address: 'Av. Las Torres, Toluca',
	// 		phone_number: '555-345-6780',
	// 		email: 'tomas.vargas@empresa.com',
	// 		hire_date: '2020-02-14',
	// 		salary: 46000,
	// 		in_time: '08:30',
	// 		out_time: '17:30',
	// 		password: 'hashedpassword13',
	// 		role: 'user',
	// 		position: 'Accountant',
	// 		status: 'active',
	// 		img: 'https://i.pravatar.cc/20'
	// 	},
	// 	{
	// 		id: 'EMP014',
	// 		name: 'Camila Herrera',
	// 		address: 'Centro Histórico, Oaxaca',
	// 		phone_number: '555-456-7891',
	// 		email: 'camila.herrera@empresa.com',
	// 		hire_date: '2023-03-01',
	// 		salary: 39000,
	// 		in_time: '10:00',
	// 		out_time: '19:00',
	// 		password: 'hashedpassword14',
	// 		role: 'user',
	// 		position: 'Office Manager',
	// 		status: 'inactive',
	// 		img: 'https://i.pravatar.cc/20'
	// 	},
	// 	{
	// 		id: 'EMP015',
	// 		name: 'Mateo Lozano',
	// 		address: 'Col. Santa Fe, CDMX',
	// 		phone_number: '555-567-8902',
	// 		email: 'mateo.lozano@empresa.com',
	// 		hire_date: '2021-09-09',
	// 		salary: 55000,
	// 		in_time: '07:00',
	// 		out_time: '16:00',
	// 		password: 'hashedpassword15',
	// 		role: 'leader',
	// 		position: 'DevOps Engineer',
	// 		status: 'active',
	// 		img: 'https://i.pravatar.cc/20' 	
	// 	},
    // ]